// <auto-generated />
namespace PBEM
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.toolStripButtonLogOn = new System.Windows.Forms.ToolStripButton();
            this.toolStripComboBoxGameList = new System.Windows.Forms.ToolStripComboBox();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripProgressBar1 = new System.Windows.Forms.ToolStripProgressBar();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.settingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.changePasswordToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.adminToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.createNewAccountFileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.loadDropBoxExplorerToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.userAccountSetupToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.panelMainDisplay = new System.Windows.Forms.Panel();
            this.toolStrip1.SuspendLayout();
            this.statusStrip1.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // toolStrip1
            // 
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripButtonLogOn,
            this.toolStripComboBoxGameList,
            this.toolStripSeparator1});
            this.toolStrip1.Location = new System.Drawing.Point(0, 24);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(670, 25);
            this.toolStrip1.TabIndex = 0;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // toolStripButtonLogOn
            // 
            this.toolStripButtonLogOn.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonLogOn.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonLogOn.Image")));
            this.toolStripButtonLogOn.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonLogOn.Name = "toolStripButtonLogOn";
            this.toolStripButtonLogOn.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonLogOn.Text = "Log On";
            this.toolStripButtonLogOn.Click += new System.EventHandler(this.ToolStripButtonLogOn_Click);
            // 
            // toolStripComboBoxGameList
            // 
            this.toolStripComboBoxGameList.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.toolStripComboBoxGameList.Name = "toolStripComboBoxGameList";
            this.toolStripComboBoxGameList.Size = new System.Drawing.Size(121, 25);
            this.toolStripComboBoxGameList.SelectedIndexChanged += new System.EventHandler(this.ToolStripComboBoxGameList_SelectedIndexChanged);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(6, 25);
            // 
            // statusStrip1
            // 
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabel1,
            this.toolStripProgressBar1});
            this.statusStrip1.Location = new System.Drawing.Point(0, 435);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(670, 22);
            this.statusStrip1.TabIndex = 1;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(0, 17);
            // 
            // toolStripProgressBar1
            // 
            this.toolStripProgressBar1.Name = "toolStripProgressBar1";
            this.toolStripProgressBar1.Size = new System.Drawing.Size(100, 16);
            this.toolStripProgressBar1.Visible = false;
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.optionsToolStripMenuItem,
            this.adminToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(670, 24);
            this.menuStrip1.TabIndex = 2;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // optionsToolStripMenuItem
            // 
            this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.settingsToolStripMenuItem,
            this.changePasswordToolStripMenuItem});
            this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
            this.optionsToolStripMenuItem.Size = new System.Drawing.Size(61, 20);
            this.optionsToolStripMenuItem.Text = "Options";
            // 
            // settingsToolStripMenuItem
            // 
            this.settingsToolStripMenuItem.Name = "settingsToolStripMenuItem";
            this.settingsToolStripMenuItem.Size = new System.Drawing.Size(168, 22);
            this.settingsToolStripMenuItem.Text = "Settings";
            this.settingsToolStripMenuItem.Click += new System.EventHandler(this.SettingsToolStripMenuItem_Click);
            // 
            // changePasswordToolStripMenuItem
            // 
            this.changePasswordToolStripMenuItem.Name = "changePasswordToolStripMenuItem";
            this.changePasswordToolStripMenuItem.Size = new System.Drawing.Size(168, 22);
            this.changePasswordToolStripMenuItem.Text = "Change Password";
            // 
            // adminToolStripMenuItem
            // 
            this.adminToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.createNewAccountFileToolStripMenuItem,
            this.loadDropBoxExplorerToolStripMenuItem,
            this.userAccountSetupToolStripMenuItem});
            this.adminToolStripMenuItem.Name = "adminToolStripMenuItem";
            this.adminToolStripMenuItem.Size = new System.Drawing.Size(55, 20);
            this.adminToolStripMenuItem.Text = "Admin";
            // 
            // createNewAccountFileToolStripMenuItem
            // 
            this.createNewAccountFileToolStripMenuItem.Name = "createNewAccountFileToolStripMenuItem";
            this.createNewAccountFileToolStripMenuItem.Size = new System.Drawing.Size(204, 22);
            this.createNewAccountFileToolStripMenuItem.Text = "Create New Account File";
            this.createNewAccountFileToolStripMenuItem.Click += new System.EventHandler(this.CreateNewAccountFileToolStripMenuItem_Click);
            // 
            // loadDropBoxExplorerToolStripMenuItem
            // 
            this.loadDropBoxExplorerToolStripMenuItem.Name = "loadDropBoxExplorerToolStripMenuItem";
            this.loadDropBoxExplorerToolStripMenuItem.Size = new System.Drawing.Size(204, 22);
            this.loadDropBoxExplorerToolStripMenuItem.Text = "Load Server Explorer";
            this.loadDropBoxExplorerToolStripMenuItem.Click += new System.EventHandler(this.LoadServerExplorerToolStripMenuItem_Click);
            // 
            // userAccountSetupToolStripMenuItem
            // 
            this.userAccountSetupToolStripMenuItem.Name = "userAccountSetupToolStripMenuItem";
            this.userAccountSetupToolStripMenuItem.Size = new System.Drawing.Size(204, 22);
            this.userAccountSetupToolStripMenuItem.Text = "User Account Manager";
            this.userAccountSetupToolStripMenuItem.Click += new System.EventHandler(this.UserAccountSetupToolStripMenuItem_Click);
            // 
            // panelMainDisplay
            // 
            this.panelMainDisplay.AutoSize = true;
            this.panelMainDisplay.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelMainDisplay.Location = new System.Drawing.Point(0, 49);
            this.panelMainDisplay.Name = "panelMainDisplay";
            this.panelMainDisplay.Size = new System.Drawing.Size(670, 386);
            this.panelMainDisplay.TabIndex = 3;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.ClientSize = new System.Drawing.Size(670, 457);
            this.Controls.Add(this.panelMainDisplay);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.toolStrip1);
            this.Controls.Add(this.menuStrip1);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Play By Email Tool";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.ToolStripButton toolStripButtonLogOn;
        private System.Windows.Forms.ToolStripComboBox toolStripComboBoxGameList;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripProgressBar toolStripProgressBar1;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem adminToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem loadDropBoxExplorerToolStripMenuItem;
        private System.Windows.Forms.Panel panelMainDisplay;
        private System.Windows.Forms.ToolStripMenuItem settingsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem createNewAccountFileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem userAccountSetupToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem changePasswordToolStripMenuItem;
    }
}

