// <auto-generated />
namespace PBEM.BloodBowl
{
    partial class BloodBowlToolbar
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(BloodBowlToolbar));
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.gameToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.testToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.startToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.toolStripButtonMain = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonTeamManager = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonGameManger = new System.Windows.Forms.ToolStripButton();
            this.adminToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip1.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.gameToolStripMenuItem,
            this.adminToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(445, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // gameToolStripMenuItem
            // 
            this.gameToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.testToolStripMenuItem,
            this.startToolStripMenuItem});
            this.gameToolStripMenuItem.Name = "gameToolStripMenuItem";
            this.gameToolStripMenuItem.Size = new System.Drawing.Size(50, 20);
            this.gameToolStripMenuItem.Text = "Game";
            // 
            // testToolStripMenuItem
            // 
            this.testToolStripMenuItem.Name = "testToolStripMenuItem";
            this.testToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.testToolStripMenuItem.Text = "Test";
            // 
            // startToolStripMenuItem
            // 
            this.startToolStripMenuItem.Name = "startToolStripMenuItem";
            this.startToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.startToolStripMenuItem.Text = "Start";
            // 
            // toolStrip1
            // 
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripButtonMain,
            this.toolStripButtonTeamManager,
            this.toolStripButtonGameManger});
            this.toolStrip1.Location = new System.Drawing.Point(0, 24);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(445, 25);
            this.toolStrip1.TabIndex = 1;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // toolStripButtonMain
            // 
            this.toolStripButtonMain.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonMain.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonMain.Image")));
            this.toolStripButtonMain.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonMain.Name = "toolStripButtonMain";
            this.toolStripButtonMain.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonMain.Text = "Main";
            this.toolStripButtonMain.Click += new System.EventHandler(this.ToolStripButtonMain_Click);
            // 
            // toolStripButtonTeamManager
            // 
            this.toolStripButtonTeamManager.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonTeamManager.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonTeamManager.Image")));
            this.toolStripButtonTeamManager.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonTeamManager.Name = "toolStripButtonTeamManager";
            this.toolStripButtonTeamManager.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonTeamManager.Text = "Team Manager";
            this.toolStripButtonTeamManager.Click += new System.EventHandler(this.ToolStripButtonTeamManager_Click_1);
            // 
            // toolStripButtonGameManger
            // 
            this.toolStripButtonGameManger.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripButtonGameManger.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonGameManger.Image")));
            this.toolStripButtonGameManger.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonGameManger.Name = "toolStripButtonGameManger";
            this.toolStripButtonGameManger.Size = new System.Drawing.Size(23, 22);
            this.toolStripButtonGameManger.Text = "Game Manager";
            this.toolStripButtonGameManger.Click += new System.EventHandler(this.ToolStripButtonGameManger_Click);
            // 
            // adminToolStripMenuItem
            // 
            this.adminToolStripMenuItem.Name = "adminToolStripMenuItem";
            this.adminToolStripMenuItem.Size = new System.Drawing.Size(55, 20);
            this.adminToolStripMenuItem.Text = "Admin";
            // 
            // BloodBowlToolbar
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.toolStrip1);
            this.Controls.Add(this.menuStrip1);
            this.Name = "BloodBowlToolbar";
            this.Size = new System.Drawing.Size(445, 67);
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem gameToolStripMenuItem;
        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton toolStripButtonMain;
        private System.Windows.Forms.ToolStripButton toolStripButtonTeamManager;
        private System.Windows.Forms.ToolStripButton toolStripButtonGameManger;
        private System.Windows.Forms.ToolStripMenuItem testToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem startToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem adminToolStripMenuItem;
    }
}
